In [106]:
import numpy as np
import pandas as pd
#visualization
import matplotlib.pyplot as plt
import seaborn as sns 

from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error,r2_score
# clustering
from sklearn.cluster import KMeans

In [2]:
df=pd.read_csv("C:/Users/athul/Downloads/Customer Churn.csv")

In [3]:
df.head()

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
0              8          0                    38               0   
1              0          0                    39               0   
2             10          0                    37               0   
3             10          0                    38               0   
4              3          0                    38               0   

   Seconds of Use  Frequency of use  Frequency of SMS  \
0            4370                71                 5   
1             318                 5                 7   
2            2453                60               359   
3            4198                66                 1   
4            2393                58                 2   

   Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
0                       17          3            1       1   30   
1                        4          2            1       2   25   
2                       24          3            1       1   30   
3                       35          1            1       1   15   
4                       33          1            1       1   15   

   Customer Value         FN        FP  Churn  
0         197.640   177.8760   69.7640      0  
1          46.035    41.4315   60.0000      0  
2        1536.520  1382.8680  203.6520      0  
3         240.020   216.0180   74.0020      0  
4         145.805   131.2245   64.5805      0

In [4]:
df.isnull().sum()

Call  Failure              0
Complains                  0
Subscription  Length       0
Charge  Amount             0
Seconds of Use             0
Frequency of use           0
Frequency of SMS           0
Distinct Called Numbers    0
Age Group                  0
Tariff Plan                0
Status                     0
Age                        0
Customer Value             0
FN                         0
FP                         0
Churn                      0
dtype: int64

In [5]:
df=df.drop(['Subscription  Length','Frequency of use','Frequency of SMS','Seconds of Use','Distinct Called Numbers','Age Group','Age'],axis=1)

In [6]:
df.head()

Call  Failure  Complains  Charge  Amount  Tariff Plan  Status  \
0              8          0               0            1       1   
1              0          0               0            1       2   
2             10          0               0            1       1   
3             10          0               0            1       1   
4              3          0               0            1       1   

   Customer Value         FN        FP  Churn  
0         197.640   177.8760   69.7640      0  
1          46.035    41.4315   60.0000      0  
2        1536.520  1382.8680  203.6520      0  
3         240.020   216.0180   74.0020      0  
4         145.805   131.2245   64.5805      0

In [15]:
sc=StandardScaler()

In [17]:
df['Customer Value']=sc.fit_transform(df['Customer Value'].values.reshape(-1,1))
df['FN']=sc.fit_transform(df['FN'].values.reshape(-1,1))
df['FP']=sc.fit_transform(df['FP'].values.reshape(-1,1))

In [18]:
df.head()

Call  Failure  Complains  Charge  Amount  Tariff Plan  Status  \
0              8          0               0            1       1   
1              0          0               0            1       2   
2             10          0               0            1       1   
3             10          0               0            1       1   
4              3          0               0            1       1   

   Customer Value        FN        FP  Churn  
0       -0.528759 -0.528759 -0.562750      0  
1       -0.822036 -0.822036 -0.755272      0  
2        2.061285  2.061285  2.077183      0  
3       -0.446775 -0.446775 -0.479188      0  
4       -0.629033 -0.629033 -0.664956      0

In [20]:
df['Churn'].value_counts()

Churn
0    2655
1     495
Name: count, dtype: int64

In [21]:
X = df.drop('Churn',axis=1)

In [22]:
X.head()

Call  Failure  Complains  Charge  Amount  Tariff Plan  Status  \
0              8          0               0            1       1   
1              0          0               0            1       2   
2             10          0               0            1       1   
3             10          0               0            1       1   
4              3          0               0            1       1   

   Customer Value        FN        FP  
0       -0.528759 -0.528759 -0.562750  
1       -0.822036 -0.822036 -0.755272  
2        2.061285  2.061285  2.077183  
3       -0.446775 -0.446775 -0.479188  
4       -0.629033 -0.629033 -0.664956

In [23]:
Y = df['Churn']

In [24]:
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: Churn, dtype: int64

In [27]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

In [28]:
X_train.head()

Call  Failure  Complains  Charge  Amount  Tariff Plan  Status  \
3082              5          0               2            1       1   
1454              0          0               0            1       1   
1498              0          0               0            1       1   
2561             18          0               0            1       2   
549               0          1               0            1       1   

      Customer Value        FN        FP  
3082       -0.860223 -0.860223 -0.755272  
1454       -0.703404 -0.703404 -0.740760  
1498        0.917463  0.917463  0.911328  
2561       -0.383904 -0.383904 -0.415106  
549        -0.841681 -0.841681 -0.755272

In [29]:
X_test.head()

Call  Failure  Complains  Charge  Amount  Tariff Plan  Status  \
2965             14          0               3            1       1   
969               3          0               0            1       1   
1385              0          0               0            1       1   
1233             21          0               3            1       1   
2996             23          0               2            1       1   

      Customer Value        FN        FP  
2965        1.233712  1.233712  1.233669  
969         3.096341  3.096341  3.132176  
1385       -0.630870 -0.630870 -0.666829  
1233        0.515167  0.515167  0.501283  
2996       -0.361648 -0.361648 -0.392421

In [ ]:
# Logistic Regression

In [30]:
LR = LogisticRegression()

In [31]:
LR.fit(X_train,Y_train)

LogisticRegression()

In [32]:
Y_pred=LR.predict(X_test)

In [33]:
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [34]:
accuracy_score(Y_pred,Y_test)

0.8899470899470899

In [ ]:
# Decision Tree

In [37]:
dt=DecisionTreeClassifier()

In [38]:
dt.fit(X_train,Y_train)

DecisionTreeClassifier()

In [39]:
Y_pred = dt.predict(X_test)

In [40]:
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [41]:
accuracy_score(Y_pred,Y_test)

0.873015873015873

In [94]:
# Random Forest

In [42]:
rf=RandomForestClassifier()

In [43]:
rf.fit(X_train,Y_train)

RandomForestClassifier()

In [44]:
Y_pred = rf.predict(X_test)

In [45]:
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [46]:
accuracy_score(Y_pred,Y_test)

0.8931216931216931

In [ ]:
# SVM

In [49]:
sv = svm.SVC(kernel='linear', random_state=0) 

In [50]:
sv.fit(X_train,Y_train)

SVC(kernel='linear', random_state=0)

In [52]:
Y_pred = sv.predict(X_test)

In [53]:
accuracy_score(Y_pred,Y_test)

0.8825396825396825

In [54]:
sv = svm.SVC(kernel='rbf', random_state=0) 

In [55]:
sv.fit(X_train,Y_train)

SVC(random_state=0)

In [56]:
Y_pred = sv.predict(X_test)

In [57]:
accuracy_score(Y_pred,Y_test)

0.8888888888888888

In [58]:
sv = svm.SVC(kernel='poly', random_state=0) 

In [60]:
sv.fit(X_train,Y_train)

SVC(kernel='poly', random_state=0)

In [61]:
Y_pred = sv.predict(X_test)

In [62]:
accuracy_score(Y_pred,Y_test)

0.8497354497354498

In [ ]:
# GRADIENT DESCENT

In [90]:
sgd = SGDClassifier()

In [91]:
sgd.fit(X_train,Y_train)

SGDClassifier()

In [92]:
Y_pred = sgd.predict(X_test)

In [93]:
accuracy_score(Y_pred,Y_test)

0.8772486772486773

In [ ]:
# KNN

In [73]:
knn = KNeighborsClassifier()

In [74]:
knn.fit(X_train,Y_train)

KNeighborsClassifier()

In [75]:
Y_pred=knn.predict(X_test)

In [77]:
accuracy_score(Y_pred,Y_test)

0.8783068783068783

In [81]:
df.head(10)

Call  Failure  Complains  Charge  Amount  Tariff Plan  Status  \
0              8          0               0            1       1   
1              0          0               0            1       2   
2             10          0               0            1       1   
3             10          0               0            1       1   
4              3          0               0            1       1   
5             11          0               1            1       1   
6              4          0               0            1       1   
7             13          0               2            1       1   
8              7          0               0            1       1   
9              7          0               1            1       1   

   Customer Value        FN        FP  Churn  
0       -0.528759 -0.528759 -0.562750      0  
1       -0.822036 -0.822036 -0.755272      0  
2        2.061285  2.061285  2.077183      0  
3       -0.446775 -0.446775 -0.479188      0  
4       -0.629033 -0.629033 -0.664956      0  
5       -0.365024 -0.365024 -0.395862      0  
6        1.479856  1.479856  1.484554      0  
7        0.917850  0.917850  0.911722      0  
8        0.167734  0.167734  0.147158      0  
9       -0.539824 -0.539824 -0.574029      0

In [96]:
gbc=GradientBoostingClassifier()

In [97]:
gbc.fit(X_train,Y_train)

GradientBoostingClassifier()

In [98]:
Y_pred=gbc.predict(X_test)

In [99]:
accuracy_score(Y_pred,Y_test)

0.891005291005291

In [ ]:
# Gaussian Naive Bayes Classifier 

In [101]:
nb=GaussianNB()

In [102]:
nb.fit(X_train,Y_train)

GaussianNB()

In [103]:
Y_pred=nb.predict(X_test)

In [104]:
accuracy_score(Y_pred,Y_test)

0.6402116402116402

In [ ]:
# Multinomial Naive Bayes Classifier 

In [109]:
mNB = MultinomialNB()

In [112]:
mNB.fit(X_train,Y_train)

ValueError: Negative values in data passed to MultinomialNB (input X)