In [1]:
#One Dimensional Array

In [17]:
import numpy as np

list1 = [1,2,3,4]
arr1 = np.array(list1)

print(arr1)

print(arr1.ndim)

print(arr1*2)

print(list1*2)

type(arr1)

arr2 = np.array([10,20,30,40])
print(arr2)

[1 2 3 4]
1
[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]
[10 20 30 40]


In [14]:
#Two Dimensional Array

In [26]:
import numpy as np
arr1 = np.array([
    [1,2,3], [4,5,6], [7,8,9], [10,11,12]
])
print(arr1)

print(arr1.ndim)

arr2 = np.array(
    [
        [10,20,30], [40,50,60]
    ]
)
print(arr2)
arr2.size

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
[[10 20 30]
 [40 50 60]]


6

In [27]:
#shape of an Array

In [34]:
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1)

np.shape(arr1)
#or
arr1.shape

[1 2 3 4]


(4,)

In [36]:
arr2 = np.array([
    [1,2,3], [4,5,6], [7,8,9], [10,11,12]
])
print(arr2)
arr2.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

In [37]:
arr3 = np.array([
    [[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
    [[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
    [[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
])
print(arr3)

np.shape(arr3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


(3, 4, 3)

In [39]:
#1D to 2D

In [44]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

newArr1 = arr1.reshape(2,3)
print(newArr1)
newArr1.shape

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


(2, 3)

In [49]:
# Reshape

In [50]:
arr2 = np.array([1,2,3,4,5,6,7,8])
print(arr2)

newArr2 = arr2.reshape(2,2,2)
print(newArr2)

[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [51]:
arr4 = np.array([1,2,3,4,5,6])
print(arr4)

newArr4 = arr4.reshape(2,3)
print(newArr4)

newArr4 = newArr4.reshape(-1)
print(newArr4)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [52]:
# Numpy Data Types

In [56]:
arr1 = np.array([1,2,3,4])
print(arr1.dtype)

int32
