In [1]:
#Naive Bayes

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris

In [7]:
x,y=load_iris(return_X_y=True)

In [8]:
pd.DataFrame(x)

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.20,random_state=42)

In [10]:
classifier = GaussianNB()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

In [13]:
result = confusion_matrix(y_test,y_pred)
print("Confusion Matrix: ")
print(result)

Confusion Matrix: 
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [14]:
result1 = classification_report(y_test,y_pred)
print("Classification Report: ")
print(result1)

Classification Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [15]:
result2 = accuracy_score(y_test,y_pred)
print("Accuracy Score: ")
print(result2)

Accuracy Score: 
1.0
