In [1]:
#Program to multiply 2 given arrays of same size element by element

In [2]:
import numpy as np

num1 = np.array([[2, 5, 2],
                 [1, 5, 5]
                ])
num2 = np.array([
    [5, 3, 4],
    [3, 2, 5]
])
print("Array 1 = ",num1)
print("Array 2 = ",num2)
print("\nMultiply the two arrays of same size element by element:")
print(np.multiply(num1, num2))

Array 1 =  [[2 5 2]
 [1 5 5]]
Array 2 =  [[5 3 4]
 [3 2 5]]

Multiply the two arrays of same size element by element:
[[10 15  8]
 [ 3 10 25]]


In [3]:
#Program to create an element-wise comparison (>,<,>=)

In [4]:
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])
print("Original Numbers are:",x,y)
print("Comparison - GREATER: ")
print(np.greater(x, y))
print("Comparison - GREATER EQUAL: ")
print(np.greater_equal(x, y))
print("Comparison - LESSER: ")
print(np.less(x, y))

Original Numbers are: [3 5] [2 5]
Comparison - GREATER: 
[ True False]
Comparison - GREATER EQUAL: 
[ True  True]
Comparison - LESSER: 
[False False]


In [5]:
#program to create an array of all even int from 30 to 70

In [6]:
import numpy as np
array = np.arange(30,71,2)
print("Array of all even integers from 30 to 70 are: ")
print(array)

Array of all even integers from 30 to 70 are: 
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
#create a 3*3 matrix

In [7]:
import numpy as np
array_3D = np.identity(3)
print("3*3 matrix: ")
print(array_3D)

3*3 matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#create a 5*5 zero matrix with elements on the main diagonal

In [8]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
#program to compute "Sum of all Elements" , "Sum of each coloumn" , "Sum of each row"

In [9]:
import numpy as np
x = np.array([
    [0,1], [2,3]
])
print("original array:",x)
print("Sum of all Elements: ")
print(np.sum(x))
print("Sum of each coloumn: ")
print(np.sum(x, axis=0))
print("Sum of each row: ")
print(np.sum(x, axis=1))

original array: [[0 1]
 [2 3]]
Sum of all Elements: 
6
Sum of each coloumn: 
[2 4]
Sum of each row: 
[1 5]
